name: Create and save SVM model
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths:
    - 'data/*/**'
    - 'train.py'

jobs:
  train:
    # Job name is Greeting
    name: Train model
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Train model
        run: |
          python3 train.py > stats.txt
      - name: Upload binaries to release linux
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./svm.pkl
          asset_name: svm.pkl
          tag: v0.1
          overwrite: true
      - name: Upload stats to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./stats.txt
          asset_name: stats.txt
          tag: v0.1
          overwrite: true
