name: Create and save SVM model
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths:
    - 'data/*/**'
    - 'train.py'
    - 'collect.py'
    - '.github/workflows/create_model.yml'

jobs:
  train:
    name: Train model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip3 install -r requirements.txt
      - run: python3 train.py > stats.txt
      - name: Upload binaries to release linux
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./svm.pkl
          asset_name: svm.pkl
          tag: v0.1
          overwrite: true
      - name: Upload stats to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./stats.txt
          asset_name: stats.txt
          tag: v0.1
          overwrite: true
  collect:
    name: Collect traces original
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Start server
        run: |
          git clone --depth=1 https://github.com/wenhao1006/SEISMIC/
          cd SEISMIC/YetAnotherZECMiner
          perl server.pl &
      - run: pip3 install -r requirements.txt
      - run: ./automation/exec_selenium.py > results
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./automation/geckodriver.log
  collect_rand:
    name: Collect traces randomized
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - run: pip3 install -r requirements.txt
      - name: Install wabt
        run: |
          git clone https://github.com/WebAssembly/wabt && cd wabt && mkdir build && cd build && cmake .. && cmake --build .
      - run: export PATH=./wabt/build:$PATH && cd automation && mkdir out && python3 collect.py 
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: ./automation/out
